---
- hosts: localhost
  gather_facts: no
  vars:
    # ServiceNow Configuration
    servicenow_instance: "https://dev247928.service-now.com/"
    servicenow_username: "admin"
    servicenow_password: "%ml4Vs9RXE/s"
    
    # Specific Workflow Configuration
    target_workflow_name: "Azure Password Reset Flow"

  tasks:
    - name: Validate Request Details
      block:
        - name: Fetch Detailed Request Information
          uri:
            url: "{{ servicenow_instance }}/api/now/table/sc_request/{{ request_id }}"
            method: GET
            url_username: "{{ servicenow_username }}"
            url_password: "{{ servicenow_password }}"
            force_basic_auth: yes
            return_content: yes
            status_code: 200
          register: request_details

        - name: Extract Request Variables
          uri:
            url: "{{ servicenow_instance }}/api/now/table/sc_req_item"
            method: GET
            url_username: "{{ servicenow_username }}"
            url_password: "{{ servicenow_password }}"
            force_basic_auth: yes
            return_content: yes
            params:
              sysparm_query: request={{ request_id }}
          register: request_items

    - name: Process Azure Password Reset
      block:
        - name: Verify Request Approval Status
          assert:
            that:
              - request_details.json.result.state == 'APPROVED'
            fail_msg: "Request has not been approved"

        - name: Extract User Details
          set_fact:
            user_principle_name: "{{ request_items.json.result[0].variables | from_json | json_query('user_principle_name') }}"

        - name: Launch Azure Password Reset Workflow
          awx.awx.job_launch:
            job_template: "Azure Password Reset"
            extra_vars:
              user_principle_name: "{{ user_principle_name }}"
              request_id: "{{ request_id }}"
          register: workflow_launch

        - name: Update ServiceNow Request Status
          uri:
            url: "{{ servicenow_instance }}/api/now/table/sc_request/{{ request_id }}"
            method: PATCH
            url_username: "{{ servicenow_username }}"
            url_password: "{{ servicenow_password }}"
            force_basic_auth: yes
            body_format: json
            body:
              state: "3"  # Completed state
              comments: "Password reset workflow executed successfully"
            status_code: 200
          register: status_update

        - name: Log Workflow Execution
          debug:
            msg:
              - "Azure Password Reset Initiated"
              - "User: {{ user_principle_name }}"
              - "Workflow Launch ID: {{ workflow_launch.id }}"
              - "Workflow Status: {{ workflow_launch.status }}"

      rescue:
        - name: Handle Workflow Execution Error
          debug:
            msg: "Failed to execute Azure Password Reset workflow"

        - name: Update ServiceNow with Error Status
          uri:
            url: "{{ servicenow_instance }}/api/now/table/sc_request/{{ request_id }}"
            method: PATCH
            url_username: "{{ servicenow_username }}"
            url_password: "{{ servicenow_password }}"
            force_basic_auth: yes
            body_format: json
            body:
              state: "4"  # Error state
              comments: "Failed to execute password reset workflow"
            status_code: 200
