---
- name: Trigger ServiceNow Catalog and Execute Workflow
  hosts: localhost
  gather_facts: no

  vars:
    servicenow_instance: "https://dev247928.service-now.com"    # Your ServiceNow instance
    servicenow_username: "admin"                                # ServiceNow username
    servicenow_password: "%ml4Vs9RXE/s"                         # ServiceNow password
    catalog_sys_id: "d58f4b528388e210d081f696feaad399"          # Catalog sys_id
    variables:                                                  # Catalog variables to pass
      user_email: "Akhilakki@amitomar63gmail.onmicrosoft.com"
      password: "NewPassword@123"

  tasks:
    # ✅ Step 1: Add Catalog Item to Cart
    - name: Add Catalog Item to Cart
      uri:
        url: "{{ servicenow_instance }}/api/sn_sc/cart/{% raw %}add_item{% endraw %}"
        method: POST
        user: "{{ servicenow_username }}"
        password: "{{ servicenow_password }}"
        force_basic_auth: yes
        headers:
          Content-Type: "application/json"
        body:
          sys_id: "{{ catalog_sys_id }}"
          quantity: 1
          variables: "{{ variables }}"
        body_format: json
        return_content: yes
        status_code: [200, 201]
      register: cart_response

    - name: Display Cart Response
      debug:
        msg:
          - "Item added to cart!"
          - "Cart Item ID: {{ cart_response.json.result.sys_id }}"

    # ✅ Step 2: Submit the Cart
    - name: Submit the Cart
      uri:
        url: "{{ servicenow_instance }}/api/sn_sc/cart/checkout"
        method: POST
        user: "{{ servicenow_username }}"
        password: "{{ servicenow_password }}"
        force_basic_auth: yes
        headers:
          Content-Type: "application/json"
        body_format: json
        return_content: yes
        status_code: [200, 201]
      register: checkout_response

    - name: Display Checkout Response
      debug:
        msg:
          - "Order successfully placed!"
          - "Request Number: {{ checkout_response.json.result.request_number }}"
          - "Request ID: {{ checkout_response.json.result.sys_id }}"
