---
- hosts: localhost
  gather_facts: no
  vars:
    # ServiceNow Configuration
    servicenow_instance: "https://dev247928.service-now.com"
    servicenow_username: "admin"
    servicenow_password: "%ml4Vs9RXE/s"

    # Catalog item details
    catalog_sys_id: "d58f4b528388e210d081f696feaad399"   # Catalog item sys_id
    user_email: "Akhilakki@amitomar63gmail.onmicrosoft.com"
    new_password: "NewPassword@123"

  tasks:
    # ✅ Step 1: Add Catalog Item to Cart
    - name: Add Catalog Item to Cart
      uri:
        url: "{{ servicenow_instance }}/api/now/table/sc_cart_item"
        method: POST
        url_username: "{{ servicenow_username }}"
        url_password: "{{ servicenow_password }}"
        force_basic_auth: yes
        headers:
          Content-Type: "application/json"
        body:
          cat_item: "{{ catalog_sys_id }}"
          quantity: 1
          variables:
            user_email: "{{ user_email }}"
            password: "{{ new_password }}"
        body_format: json
        return_content: yes
        status_code: [200, 201]
      register: cart_response

    # ✅ Step 2: Extract Cart ID
    - name: Extract Cart ID
      set_fact:
        cart_id: "{{ cart_response.json.result.cart }}"

    # ✅ Step 3: Checkout Cart to Create the Request
    - name: Checkout Cart to Create the Request
      uri:
        url: "{{ servicenow_instance }}/api/now/table/sc_request"
        method: POST
        url_username: "{{ servicenow_username }}"
        url_password: "{{ servicenow_password }}"
        force_basic_auth: yes
        headers:
          Content-Type: "application/json"
        body:
          cart: "{{ cart_id }}"
          short_description: "Password reset request for {{ user_email }}"
          requested_for: "{{ user_email }}"
          special_instructions: "Auto-triggered by Ansible playbook"
        body_format: json
        return_content: yes
        status_code: [200, 201]
      register: order_response

    # ✅ Step 4: Extract the Request ID
    - name: Extract Request ID
      set_fact:
        request_id: "{{ order_response.json.result.sys_id }}"

    # ✅ Step 5: Fetch the Request Details
    - name: Fetch Request Details
      uri:
        url: "{{ servicenow_instance }}/api/now/table/sc_request/{{ request_id }}"
        method: GET
        url_username: "{{ servicenow_username }}"
        url_password: "{{ servicenow_password }}"
        force_basic_auth: yes
        return_content: yes
        status_code: 200
      register: request_details

    - name: Debug Request Details
      debug:
        var: request_details.json

    # ✅ Step 6: Retrieve the Request Items
    - name: Retrieve Request Items
      uri:
        url: "{{ servicenow_instance }}/api/now/table/sc_req_item"
        method: GET
        url_username: "{{ servicenow_username }}"
        url_password: "{{ servicenow_password }}"
        force_basic_auth: yes
        return_content: yes
        params:
          sysparm_query: "request={{ request_id }}"
        status_code: 200
      register: request_items

    - name: Extract User Principal Name
      set_fact:
        user_principle_name: "{{ request_items.json.result[0].variables.user_principle_name }}"

    # ✅ Step 7: Trigger the AWX Workflow with Correct Name
    - name: Launch **Azure Password Reset Flow**
      awx.awx.job_launch:
        job_template: "Azure Password Reset Flow"   # ✅ Updated Workflow Name
        extra_vars:
          user_principle_name: "{{ user_principle_name }}"
          request_id: "{{ request_id }}"
      register: workflow_launch

    - name: Debug Workflow Execution
      debug:
        msg:
          - "Workflow Launched: {{ workflow_launch.id }}"
          - "Status: {{ workflow_launch.status }}"

    # ✅ Step 8: Update ServiceNow Request Status
    - name: Update ServiceNow Request Status
      uri:
        url: "{{ servicenow_instance }}/api/now/table/sc_request/{{ request_id }}"
        method: PATCH
        url_username: "{{ servicenow_username }}"
        url_password: "{{ servicenow_password }}"
        force_basic_auth: yes
        body_format: json
        body:
          state: "3"  # Completed state
          comments: "Password reset workflow executed successfully"
        status_code: 200
