---
- name: Trigger ServiceNow Catalog Item and Execute Workflow
  hosts: localhost
  gather_facts: no

  vars:
    servicenow_instance: "https://dev247928.service-now.com"    # ServiceNow instance
    servicenow_username: "admin"                                # ServiceNow username
    servicenow_password: "%ml4Vs9RXE/s"                         # ServiceNow password
    catalog_sys_id: "d58f4b528388e210d081f696feaad399"          # Catalog sys_id
    variables:                                                  # Catalog variables
      user_email: "Akhilakki@amitomar63gmail.onmicrosoft.com"
      password: "NewPassword@123"

  tasks:
    # ✅ Step 1: Create a Catalog Request
    - name: Create ServiceNow Request
      uri:
        url: "{{ servicenow_instance }}/api/now/table/sc_request"
        method: POST
        user: "{{ servicenow_username }}"
        password: "{{ servicenow_password }}"
        force_basic_auth: yes
        headers:
          Content-Type: "application/json"
        body:
          short_description: "Triggering catalog item {{ catalog_sys_id }}"
          requested_for: "{{ servicenow_username }}"
        body_format: json
        return_content: yes
        status_code: [200, 201]
      register: request_response

    - name: Extract Request ID
      set_fact:
        request_sys_id: "{{ request_response.json.result.sys_id }}"

    - name: Display Request ID
      debug:
        msg: "Catalog Request ID: {{ request_sys_id }}"

    # ✅ Step 2: Add the Catalog Item to the Request
    - name: Create Request Item
      uri:
        url: "{{ servicenow_instance }}/api/now/table/sc_req_item"
        method: POST
        user: "{{ servicenow_username }}"
        password: "{{ servicenow_password }}"
        force_basic_auth: yes
        headers:
          Content-Type: "application/json"
        body:
          request: "{{ request_sys_id }}"
          cat_item: "{{ catalog_sys_id }}"
          quantity: 1
        body_format: json
        return_content: yes
        status_code: [200, 201]
      register: item_response

    - name: Extract Request Item ID
      set_fact:
        item_sys_id: "{{ item_response.json.result.sys_id }}"

    - name: Display Request Item ID
      debug:
        msg: "Request Item ID: {{ item_sys_id }}"

    # ✅ Step 3: Add Variables to the Request Item
    - name: Add Variables to Request Item
      uri:
        url: "{{ servicenow_instance }}/api/now/table/sc_item_option"
        method: POST
        user: "{{ servicenow_username }}"
        password: "{{ servicenow_password }}"
        force_basic_auth: yes
        headers:
          Content-Type: "application/json"
        body:
          request_item: "{{ item_sys_id }}"
          name: "user_email"
          value: "{{ variables.user_email }}"
        body_format: json
        return_content: yes
        status_code: [200, 201]

    - name: Add Password Variable
      uri:
        url: "{{ servicenow_instance }}/api/now/table/sc_item_option"
        method: POST
        user: "{{ servicenow_username }}"
        password: "{{ servicenow_password }}"
        force_basic_auth: yes
        headers:
          Content-Type: "application/json"
        body:
          request_item: "{{ item_sys_id }}"
          name: "password"
          value: "{{ variables.password }}"
        body_format: json
        return_content: yes
        status_code: [200, 201]

    # ✅ Step 4: Display Final Details
    - name: Display Final Request Details
      debug:
        msg:
          - "ServiceNow Request ID: {{ request_sys_id }}"
          - "Request Item ID: {{ item_sys_id }}"
          - "Workflow Execution Triggered!"
