---
- name: Trigger ServiceNow Catalog Item with Approval and Workflow Execution
  hosts: localhost
  gather_facts: no

  vars:
    servicenow_instance: "https://dev247928.service-now.com"   # ServiceNow instance URL
    servicenow_username: "admin"                               # ServiceNow username
    servicenow_password: "%ml4Vs9RXE/s"                        # ServiceNow password
    catalog_sys_id: "d58f4b528388e210d081f696feaad399"         # Catalog sys_id
    user_email: "Akhilakki@amitomar63gmail.onmicrosoft.com"    # User email variable
    password: "NewPassword@123"                                # User password variable

  tasks:
  
    # ✅ Step 1: Trigger the Catalog Request
    - name: Create Catalog Request
      uri:
        url: "{{ servicenow_instance }}/api/now/table/sc_request"
        method: POST
        user: "{{ servicenow_username }}"
        password: "{{ servicenow_password }}"
        force_basic_auth: yes
        headers:
          Content-Type: "application/json"
        body:
          short_description: "Triggering Catalog Workflow for {{ user_email }}"
          requested_for: "{{ user_email }}"
        body_format: json
        return_content: yes
        status_code: [200, 201]
      register: request_response

    - name: Extract Request ID
      set_fact:
        request_sys_id: "{{ request_response.json.result.sys_id }}"

    - name: Display Request ID
      debug:
        msg: "Created Request ID: {{ request_sys_id }}"

    # ✅ Step 2: Create Request Item with Variables
    - name: Create Request Item in Catalog
      uri:
        url: "{{ servicenow_instance }}/api/now/table/sc_req_item"
        method: POST
        user: "{{ servicenow_username }}"
        password: "{{ servicenow_password }}"
        force_basic_auth: yes
        headers:
          Content-Type: "application/json"
        body:
          request: "{{ request_sys_id }}"
          cat_item: "{{ catalog_sys_id }}"
          quantity: 1
        body_format: json
        return_content: yes
        status_code: [200, 201]
      register: item_response

    - name: Extract Request Item ID
      set_fact:
        item_sys_id: "{{ item_response.json.result.sys_id }}"

    - name: Display Request Item ID
      debug:
        msg: "Request Item ID: {{ item_sys_id }}"

    # ✅ Step 3: Attach Variables to the RITM
    - name: Add Email Variable to Request Item
      uri:
        url: "{{ servicenow_instance }}/api/now/table/sc_item_option"
        method: POST
        user: "{{ servicenow_username }}"
        password: "{{ servicenow_password }}"
        force_basic_auth: yes
        headers:
          Content-Type: "application/json"
        body:
          request_item: "{{ item_sys_id }}"
          name: "user_email"
          value: "{{ user_email }}"
        body_format: json
        return_content: yes
        status_code: [200, 201]

    - name: Add Password Variable to Request Item
      uri:
        url: "{{ servicenow_instance }}/api/now/table/sc_item_option"
        method: POST
        user: "{{ servicenow_username }}"
        password: "{{ servicenow_password }}"
        force_basic_auth: yes
        headers:
          Content-Type: "application/json"
        body:
          request_item: "{{ item_sys_id }}"
          name: "password"
          value: "{{ password }}"
        body_format: json
        return_content: yes
        status_code: [200, 201]

    # ✅ Step 4: Trigger Manager Approval
    - name: Trigger Approval
      uri:
        url: "{{ servicenow_instance }}/api/now/table/sysapproval_approver"
        method: POST
        user: "{{ servicenow_username }}"
        password: "{{ servicenow_password }}"
        force_basic_auth: yes
        headers:
          Content-Type: "application/json"
        body:
          parent: "{{ request_sys_id }}"      # Link to the catalog request
          approver: "manager_user_id"         # Replace with Manager sys_id or username
          state: "requested"
        body_format: json
        return_content: yes
        status_code: [200, 201]

    - name: Display Approval Triggered
      debug:
        msg: "Approval request triggered for Manager!"

    # ✅ Step 5: Check for Approval Status
    - name: Wait for Approval
      uri:
        url: "{{ servicenow_instance }}/api/now/table/sysapproval_approver"
        method: GET
        user: "{{ servicenow_username }}"
        password: "{{ servicenow_password }}"
        force_basic_auth: yes
        headers:
          Content-Type: "application/json"
        body_format: json
        return_content: yes
        status_code: 200
      register: approval_response
      until: approval_response.json.result[0].state == "approved"
      retries: 15
      delay: 10

    - name: Display Approval Status
      debug:
        msg: "Approval Status: {{ approval_response.json.result[0].state }}"

    # ✅ Step 6: Trigger the Workflow Execution After Approval
    - name: Trigger Catalog Workflow Execution
      uri:
        url: "{{ servicenow_instance }}/api/now/table/sc_req_item/{{ item_sys_id }}"
        method: PATCH
        user: "{{ servicenow_username }}"
        password: "{{ servicenow_password }}"
        force_basic_auth: yes
        headers:
          Content-Type: "application/json"
        body:
          state: "closed_complete"         # Execute the workflow
          approval: "approved"
        body_format: json
        return_content: yes
        status_code: [200, 201]

    - name: Display Workflow Triggered
      debug:
        msg: "Workflow triggered successfully after manager approval!"
