---
- name: Create ServiceNow Catalog Request
  hosts: localhost
  gather_facts: no
  vars:
    servicenow_instance: "https://dev247928.service-now.com/"   # Replace with your ServiceNow instance URL
    servicenow_username: "admin"                                # Replace with your ServiceNow username
    servicenow_password: "%ml4Vs9RXE/s"                        # Replace with your ServiceNow password
    catalog_item_sys_id: "d58f4b528388e210d081f696feaad399"             # Replace with the catalog item sys_id
    short_description: "Password Reset Request via AWX"
    requested_for: "AdminAll@amitomar63gmail.onmicrosoft.com"                            # Replace with the user requesting the reset
    variables:
      email: "AdminAll@amitomar63gmail.onmicrosoft.com"                                  # Azure AD user email
      new_password: "NewPassword123!"                           # New password

  tasks:
    # Step 1: Create Catalog Request
    - name: Create Catalog Request in ServiceNow
      uri:
        url: "{{ servicenow_instance }}/api/now/table/sc_req_item"
        method: POST
        user: "{{ servicenow_username }}"
        password: "{{ servicenow_password }}"
        force_basic_auth: yes
        headers:
          Content-Type: "application/json"
        body:
          short_description: "{{ short_description }}"
          requested_for: "{{ requested_for }}"
          cat_item: "{{ catalog_item_sys_id }}"
          variables:
            email: "{{ variables.email }}"
            new_password: "{{ variables.new_password }}"
        body_format: json
        return_content: yes
        status_code: [200, 201]
      register: catalog_response

    # Step 2: Display Catalog Request Details
    - name: Display Created Catalog Request
      debug:
        msg: 
          - "Request ID: {{ catalog_response.json.result.sys_id }}"
          - "Description: {{ catalog_response.json.result.short_description }}"
          - "Requested For: {{ catalog_response.json.result.requested_for }}"

