---
- name: Create ServiceNow Catalog with Variables via AWX
  hosts: localhost
  gather_facts: no
  vars:
    servicenow_instance: "https://dev247928.service-now.com/"  # Replace with your ServiceNow instance
    servicenow_username: "admin"         # Replace with your ServiceNow username
    servicenow_password: "%ml4Vs9RXE/s"  # Replace with your ServiceNow password
    catalog_name: "Password Trigger"
    catalog_description: "Trigger Azure AD Password Reset with Email and Password Variables"
    variable_1_name: "user_email"
    variable_1_label: "Azure AD User Email"
    variable_2_name: "new_password"
    variable_2_label: "New Password"

  tasks:
    # Step 1: Create Catalog Item
    - name: Create Catalog Item in ServiceNow
      uri:
        url: "{{ servicenow_instance }}/api/now/table/sc_cat_item"
        method: POST
        user: "{{ servicenow_username }}"
        password: "{{ servicenow_password }}"
        force_basic_auth: yes
        headers:
          Content-Type: "application/json"
        body:
          name: "{{ catalog_name }}"
          short_description: "{{ catalog_description }}"
          active: true
          sys_class_name: "sc_cat_item"
          catalog: "YOUR_CATALOG_SYS_ID"    # Replace with your catalog sys_id
        body_format: json
        return_content: yes
        status_code: [200, 201]   # ✅ Accept both 200 and 201 as valid responses
      register: catalog_response

    # Step 2: Debug Catalog Creation Response
    - name: Debug the catalog creation response
      debug:
        var: catalog_response

    # Step 3: Extract sys_id from catalog response
    - name: Extract sys_id from catalog response
      set_fact:
        catalog_sys_id: "{{ catalog_response.json.result.sys_id }}"

    # Step 4: Validate sys_id extraction
    - name: Validate sys_id extraction
      fail:
        msg: "Failed to extract catalog sys_id!"
      when: catalog_sys_id is not defined or catalog_sys_id == ""

    # Step 5: Add Variable 1 (User Email) - Single Line Text
    - name: Add Variable 1 (User Email)
      uri:
        url: "{{ servicenow_instance }}/api/now/table/item_option_new"
        method: POST
        user: "{{ servicenow_username }}"
        password: "{{ servicenow_password }}"
        force_basic_auth: yes
        headers:
          Content-Type: "application/json"
        body:
          name: "{{ variable_1_name }}"
          label: "{{ variable_1_label }}"
          question: "{{ variable_1_name }}"     # ✅ Question same as name
          type: "1"  # ✅ Single Line Text
          cat_item: "{{ catalog_sys_id }}"
          mandatory: true
        body_format: json
        return_content: yes
        status_code: [200, 201]
      register: var1_response

    # Step 6: Add Variable 2 (New Password) - Single Line Text
    - name: Add Variable 2 (New Password)
      uri:
        url: "{{ servicenow_instance }}/api/now/table/item_option_new"
        method: POST
        user: "{{ servicenow_username }}"
        password: "{{ servicenow_password }}"
        force_basic_auth: yes
        headers:
          Content-Type: "application/json"
        body:
          name: "{{ variable_2_name }}"
          label: "{{ variable_2_label }}"
          question: "{{ variable_2_name }}"    # ✅ Question same as name
          type: "1"  # ✅ Single Line Text
          cat_item: "{{ catalog_sys_id }}"
          mandatory: true
        body_format: json
        return_content: yes
        status_code: [200, 201]
      register: var2_response

    # Step 7: Debug Variables Creation Response
    - name: Debug Variables Creation Response
      debug:
        msg:
          - "Catalog Item Created: {{ catalog_sys_id }}"
          - "Variable 1 ID: {{ var1_response.json.result.sys_id }}"
          - "Variable 2 ID: {{ var2_response.json.result.sys_id }}"
