---
- hosts: localhost
  gather_facts: no
  vars:
    # ServiceNow Configuration
    servicenow_instance: "https://dev247928.service-now.com/"
    servicenow_username: "admin"
    servicenow_password: "%ml4Vs9RXE/s"

  tasks:
    - name: Validate Input Parameters
      block:
        - name: Check Required Variables
          assert:
            that:
              - request_id is defined
              - request_id | length > 0
            fail_msg: "request_id must be provided when launching this playbook"

        - name: Fetch Detailed Request Information
          uri:
            url: "{{ servicenow_instance }}/api/now/table/sc_request/{{ request_id }}"
            method: GET
            url_username: "{{ servicenow_username }}"
            url_password: "{{ servicenow_password }}"
            force_basic_auth: yes
            return_content: yes
            status_code: 200
          register: request_details

        - name: Verify Request Approval Status
          assert:
            that:
              - request_details.json.result.state == 'APPROVED'
            fail_msg: "Request has not been approved or is in an invalid state"

    - name: Retrieve Request Item Details
      uri:
        url: "{{ servicenow_instance }}/api/now/table/sc_req_item"
        method: GET
        url_username: "{{ servicenow_username }}"
        url_password: "{{ servicenow_password }}"
        force_basic_auth: yes
        return_content: yes
        params:
          sysparm_query: request={{ request_id }}
      register: request_items

    - name: Extract User Details
      block:
        - name: Parse Request Variables
          set_fact:
            user_principle_name: "{{ request_items.json.result[0].variables | from_json | json_query('user_principle_name') }}"
          when: request_items.json.result[0].variables is defined

        - name: Validate Extracted User Details
          assert:
            that:
              - user_principle_name is defined
              - user_principle_name | length > 0
            fail_msg: "Could not extract user principle name from request"

    - name: Launch Azure Password Reset Workflow
      awx.awx.job_launch:
        job_template: "Azure Password Reset"
        extra_vars:
          user_principle_name: "{{ user_principle_name }}"
          request_id: "{{ request_id }}"
      register: workflow_launch

    - name: Update ServiceNow Request Status
      uri:
        url: "{{ servicenow_instance }}/api/now/table/sc_request/{{ request_id }}"
        method: PATCH
        url_username: "{{ servicenow_username }}"
        url_password: "{{ servicenow_password }}"
        force_basic_auth: yes
        body_format: json
        body:
          state: "3"  # Completed state
          comments: "Password reset workflow executed successfully"
        status_code: 200
      register: status_update

    - name: Log Workflow Execution
      debug:
        msg:
          - "Azure Password Reset Initiated"
          - "User: {{ user_principle_name }}"
          - "Workflow Launch ID: {{ workflow_launch.id }}"
          - "Workflow Status: {{ workflow_launch.status }}"

  rescue:
    - name: Handle Workflow Execution Error
      debug:
        msg: 
          - "Error in Password Reset Workflow"
          - "Request ID: {{ request_id | default('Not Provided') }}"

    - name: Update ServiceNow with Error Status
      uri:
        url: "{{ servicenow_instance }}/api/now/table/sc_request/{{ request_id }}"
        method: PATCH
        url_username: "{{ servicenow_username }}"
        url_password: "{{ servicenow_password }}"
        force_basic_auth: yes
        body_format: json
        body:
          state: "4"  # Error state
          comments: "Failed to execute password reset workflow"
        status_code: 200
      when: request_id is defined
