---
- name: Create ServiceNow Catalog Item with Variables
  hosts: localhost
  gather_facts: no
  vars:
    servicenow_instance: "https://devXXXXX.service-now.com"  # Replace with your instance
    servicenow_username: "admin"   # Replace with your username
    servicenow_password: "your_password"  # Replace with your password
    catalog_name: "Password Trigger"
    catalog_description: "Trigger Azure AD Password Reset with Email and Password Variables"
    variable_1_name: "user_email"
    variable_1_label: "Azure AD User Email"
    variable_2_name: "new_password"
    variable_2_label: "New Password"

  tasks:
    - name: Create Catalog Item in ServiceNow
      uri:
        url: "{{ servicenow_instance }}/api/now/table/sc_cat_item"
        method: POST
        user: "{{ servicenow_username }}"
        password: "{{ servicenow_password }}"
        force_basic_auth: yes
        headers:
          Content-Type: "application/json"
        body:
          name: "{{ catalog_name }}"
          short_description: "{{ catalog_description }}"
          active: true
          sys_class_name: "sc_cat_item"
          catalog: "YOUR_CATALOG_SYS_ID"    # Replace with your catalog sys_id
        body_format: json
        return_content: yes
      register: catalog_response

    - name: Debug Catalog Creation Response
      debug:
        var: catalog_response.json

    - name: Set Catalog Item ID
      set_fact:
        catalog_item_id: "{{ catalog_response.json.result.sys_id }}"

    - name: Create Variable 1 (User Email)
      uri:
        url: "{{ servicenow_instance }}/api/now/table/item_option_new"
        method: POST
        user: "{{ servicenow_username }}"
        password: "{{ servicenow_password }}"
        force_basic_auth: yes
        headers:
          Content-Type: "application/json"
        body:
          name: "{{ variable_1_name }}"
          label: "{{ variable_1_label }}"
          type: "1"    # 1 = Single Line Text
          cat_item: "{{ catalog_item_id }}"
          mandatory: true
        body_format: json
        return_content: yes
      register: var1_response

    - name: Create Variable 2 (New Password)
      uri:
        url: "{{ servicenow_instance }}/api/now/table/item_option_new"
        method: POST
        user: "{{ servicenow_username }}"
        password: "{{ servicenow_password }}"
        force_basic_auth: yes
        headers:
          Content-Type: "application/json"
        body:
          name: "{{ variable_2_name }}"
          label: "{{ variable_2_label }}"
          type: "1"    # 1 = Single Line Text
          cat_item: "{{ catalog_item_id }}"
          mandatory: true
        body_format: json
        return_content: yes
      register: var2_response

    - name: Debug Variables Creation Response
      debug:
        msg:
          - "Catalog Item Created: {{ catalog_item_id }}"
          - "Variable 1: {{ var1_response.json.result.sys_id }}"
          - "Variable 2: {{ var2_response.json.result.sys_id }}"
