---
- name: Create ServiceNow Catalog with Variables via AWX
  hosts: localhost
  gather_facts: no
  vars:
    servicenow_instance: "https://dev247928.service-now.com/"  # Replace with your ServiceNow instance
    servicenow_username: "admin"         # Replace with your ServiceNow username
    servicenow_password: "%ml4Vs9RXE/s" # Replace with your ServiceNow password
    catalog_name: "Password Trigger"
    catalog_description: "Trigger Azure AD Password Reset with Email and Password Variables"
    variable_1_name: "user_email"
    variable_1_label: "Azure AD User Email"
    variable_2_name: "new_password"
    variable_2_label: "New Password"

  tasks:
    # Step 1: Create the Catalog Item
    - name: Create Catalog Item in ServiceNow
      uri:
        url: "{{ servicenow_instance }}/api/now/table/sc_cat_item"
        method: POST
        user: "{{ servicenow_username }}"
        password: "{{ servicenow_password }}"
        force_basic_auth: yes
        headers:
          Content-Type: "application/json"
        body:
          name: "{{ catalog_name }}"
          short_description: "{{ catalog_description }}"
          active: true
          sys_class_name: "sc_cat_item"
          catalog: "YOUR_CATALOG_SYS_ID"    # Replace with your catalog sys_id
        body_format: json
        return_content: yes
      register: catalog_response

    # Step 2: Fetch the Catalog Item sys_id
    - name: Get Catalog Item sys_id
      uri:
        url: "{{ servicenow_instance }}/api/now/table/sc_cat_item?name={{ catalog_name }}"
        method: GET
        user: "{{ servicenow_username }}"
        password: "{{ servicenow_password }}"
        force_basic_auth: yes
        headers:
          Content-Type: "application/json"
        return_content: yes
      register: catalog_item_response

    - name: Debug Catalog Item sys_id
      debug:
        var: catalog_item_response.json.result[0].sys_id

    - name: Set Catalog Item ID Fact
      set_fact:
        catalog_item_id: "{{ catalog_item_response.json.result[0].sys_id }}"

    # Step 3: Create Variable 1 (User Email)
    - name: Create Variable 1 (User Email)
      uri:
        url: "{{ servicenow_instance }}/api/now/table/item_option_new"
        method: POST
        user: "{{ servicenow_username }}"
        password: "{{ servicenow_password }}"
        force_basic_auth: yes
        headers:
          Content-Type: "application/json"
        body:
          name: "{{ variable_1_name }}"
          label: "{{ variable_1_label }}"
          type: "1"  # 1 = Single Line Text
          cat_item: "{{ catalog_item_id }}"
          mandatory: true
        body_format: json
        return_content: yes
      register: var1_response

    # Step 4: Create Variable 2 (New Password)
    - name: Create Variable 2 (New Password)
      uri:
        url: "{{ servicenow_instance }}/api/now/table/item_option_new"
        method: POST
        user: "{{ servicenow_username }}"
        password: "{{ servicenow_password }}"
        force_basic_auth: yes
        headers:
          Content-Type: "application/json"
        body:
          name: "{{ variable_2_name }}"
          label: "{{ variable_2_label }}"
          type: "1"  # 1 = Single Line Text
          cat_item: "{{ catalog_item_id }}"
          mandatory: true
        body_format: json
        return_content: yes
      register: var2_response

    # Step 5: Debug the Variable Creation Responses
    - name: Debug Variables Creation Response
      debug:
        msg:
          - "Catalog Item Created: {{ catalog_item_id }}"
          - "Variable 1: {{ var1_response.json.result.sys_id }}"
          - "Variable 2: {{ var2_response.json.result.sys_id }}"
