---
- name: Order ServiceNow Catalog Item for Password Reset
  hosts: localhost
  gather_facts: no

  vars:
    servicenow_instance: "https://dev247928.service-now.com/"    # Replace with your ServiceNow instance
    servicenow_username: "admin"                            # ServiceNow username
    servicenow_password: "%ml4Vs9RXE/s"                            # ServiceNow password
    catalog_sys_id: "d58f4b528388e210d081f696feaad399"                           # Catalog item sys_id
    user_email: "Akhilakki@amitomar63gmail.onmicrosoft.com"                                  # User email
    password: "NewPassword@123"                                 # New password

  tasks:
    # Step 1: Directly Order the Catalog Item
    - name: Order Catalog Item Directly
      uri:
        url: "{{ servicenow_instance }}/api/sn_sc_servicecatalog/order_now"
        method: POST
        user: "{{ servicenow_username }}"
        password: "{{ servicenow_password }}"
        force_basic_auth: yes
        headers:
          Content-Type: "application/json"
        body:
          items:
            - sys_id: "{{ catalog_sys_id }}"                     # Catalog item sys_id
              quantity: 1
              variables:
                user_email: "{{ user_email }}"                   # User email variable
                password: "{{ password }}"                   # Password variable
        body_format: json
        return_content: yes
        status_code: [200, 201]
      register: order_response

    # Step 2: Display Order Details
    - name: Display Order Details
      debug:
        msg:
          - "Order Submitted Successfully"
          - "Request Number: {{ order_response.json.result.request_number }}"
          - "Request Sys ID: {{ order_response.json.result.sys_id }}"
