---
- name: Execute Password Reset Catalog
  hosts: localhost
  gather_facts: false
  
  # Variables that can be passed from AWX
  vars:
    # user_email: "{{ user_email | default('') }}"
    # user_password: "{{ user_password | default('') }}"
    user_email: "Akhilakki@amitomar63gmail.onmicrosoft.com"
    password: "New@123"

  tasks:
    - name: Validate Input Variables
      block:
        - name: Check if email is provided
          ansible.builtin.assert:
            that:
              - user_email | length > 0
            fail_msg: "User email must be provided"
        
        - name: Check if password is provided
          ansible.builtin.assert:
            that:
              - password | length > 0
            fail_msg: "User password must be provided"
      
    - name: Execute Password Reset Catalog
      ansible.builtin.command: 
        cmd: https://dev247928.service-now.com/now/nav/ui/classic/params/target/com.glideapp.servicecatalog_cat_item_view.do%3Fv%3D1%26sysparm_id%3Dd58f4b528388e210d081f696feaad399 "{{ user_email }}" "{{ password }}"
      register: catalog_output
      changed_when: catalog_output.rc == 0
      
    - name: Display Catalog Execution Result
      ansible.builtin.debug:
        var: catalog_output

  # # Optional: Trigger workflow after catalog execution
  # post_tasks:
  #   - name: Trigger Subsequent Workflow
  #     ansible.builtin.uri:
  #       url: "https://your-awx-server/api/v2/job_templates/workflow-template-id/launch/"
  #       method: POST
  #       user: your_awx_username
  #       password: your_awx_password
  #       force_basic_auth: yes
  #       status_code: 201
  #     when: catalog_output.rc == 0
