---
- name: Order ServiceNow Catalog Item and Trigger Workflow
  hosts: localhost
  gather_facts: no

  vars:
    servicenow_instance: "https://dev247928.service-now.com"    # ServiceNow instance
    servicenow_username: "admin"                                # ServiceNow username
    servicenow_password: "%ml4Vs9RXE/s"                         # ServiceNow password
    catalog_sys_id: "d58f4b528388e210d081f696feaad399"         # Catalog item sys_id
    user_email: "Akhilakki@amitomar63gmail.onmicrosoft.com"     # User email variable
    password: "NewPassword@123"                                 # Password variable

  tasks:
    # ✅ Step 1: Add Catalog Item to the Cart
    - name: Add Catalog Item to Cart
      uri:
        url: "{{ servicenow_instance }}/api/sn_sc/servicecatalog/cart"
        method: POST
        user: "{{ servicenow_username }}"
        password: "{{ servicenow_password }}"
        force_basic_auth: yes
        headers:
          Content-Type: "application/json"
        body:
          items: 
            - sys_id: "{{ catalog_sys_id }}"
              quantity: 1
              variables:
                user_email: "{{ user_email }}"                   # User email
                password: "{{ password }}"                       # Password
        body_format: json
        return_content: yes
        status_code: [200, 201]
      register: cart_response

    # ✅ Step 2: Extract Cart ID
    - name: Extract Cart ID
      set_fact:
        cart_id: "{{ cart_response.json.result.cart_id }}"

    # ✅ Step 3: Submit the Order
    - name: Submit the Cart Order and Trigger Workflow
      uri:
        url: "{{ servicenow_instance }}/api/sn_sc/servicecatalog/cart/{{ cart_id }}/submit_order"
        method: POST
        user: "{{ servicenow_username }}"
        password: "{{ servicenow_password }}"
        force_basic_auth: yes
        headers:
          Content-Type: "application/json"
        body_format: json
        return_content: yes
        status_code: [200, 201]
      register: order_response

    # ✅ Step 4: Display Order Details
    - name: Display Order Details
      debug:
        msg:
          - "Order Submitted Successfully"
          - "Request Number: {{ order_response.json.result.request_number }}"
          - "Request Sys ID: {{ order_response.json.result.sys_id }}"
