---
- name: Trigger ServiceNow Catalog Item and Execute Workflow
  hosts: localhost
  gather_facts: no

  vars:
    servicenow_instance: "https://dev247928.service-now.com"    # Your ServiceNow instance
    servicenow_username: "admin"                                # ServiceNow username
    servicenow_password: "%ml4Vs9RXE/s"                         # ServiceNow password
    catalog_sys_id: "d58f4b528388e210d081f696feaad399"          # The sys_id of your catalog item
    variables:                                                  # Catalog variables to pass
      user_email: "Akhilakki@amitomar63gmail.onmicrosoft.com"
      password: "NewPassword@123"

  tasks:
    # ✅ Step 1: Trigger the Catalog Item
    - name: Order ServiceNow Catalog Item
      uri:
        url: "{{ servicenow_instance }}/api/sn_sc/servicecatalog/items/{{ catalog_sys_id }}/order"
        method: POST
        user: "{{ servicenow_username }}"
        password: "{{ servicenow_password }}"
        force_basic_auth: yes
        headers:
          Content-Type: "application/json"
        body:
          variables: "{{ variables }}"
        body_format: json
        return_content: yes
        status_code: [200, 201]
      register: order_response

    # ✅ Step 2: Display Order Confirmation
    - name: Display Order Response
      debug:
        msg: 
          - "Order successfully placed!"
          - "Request Number: {{ order_response.json.result.request_number }}"
          - "Request ID: {{ order_response.json.result.sys_id }}"
