---
- name: Create ServiceNow Catalog Request for Password Reset
  hosts: localhost
  gather_facts: no

  vars:
    servicenow_instance: "https://dev247928.service-now.com"    # ServiceNow instance URL
    servicenow_username: "admin"                                # ServiceNow username
    servicenow_password: "%ml4Vs9RXE/s"                         # ServiceNow password
    catalog_sys_id: "d58f4b528388e210d081f696feaad399"          # Catalog sys_id
    user_email: "Akhilakki@amitomar63gmail.onmicrosoft.com"     # Email variable
    password: "NewPassword@123"                                 # Password variable

  tasks:
    # ✅ Step 1: Create Catalog Request
    - name: Create Catalog Request
      uri:
        url: "{{ servicenow_instance }}/api/now/table/sc_request"
        method: POST
        user: "{{ servicenow_username }}"
        password: "{{ servicenow_password }}"
        force_basic_auth: yes
        headers:
          Content-Type: "application/json"
        body:
          short_description: "Password reset request for {{ user_email }}"
          requested_for: "{{ servicenow_username }}"
        body_format: json
        return_content: yes
        status_code: [200, 201]
      register: request_response

    - name: Extract Request ID
      set_fact:
        request_sys_id: "{{ request_response.json.result.sys_id }}"

    # ✅ Step 2: Create Request Item
    - name: Create Request Item
      uri:
        url: "{{ servicenow_instance }}/api/now/table/sc_req_item"
        method: POST
        user: "{{ servicenow_username }}"
        password: "{{ servicenow_password }}"
        force_basic_auth: yes
        headers:
          Content-Type: "application/json"
        body:
          request: "{{ request_sys_id }}"
          cat_item: "{{ catalog_sys_id }}"
          quantity: 1
        body_format: json
        return_content: yes
        status_code: [200, 201]
      register: item_response

    - name: Extract Request Item ID
      set_fact:
        item_sys_id: "{{ item_response.json.result.sys_id }}"

    # ✅ Step 3: Check for Existing Tables
    - name: Check if 'sc_item_option' table exists
      uri:
        url: "{{ servicenow_instance }}/api/now/table/sc_item_option?sysparm_limit=1"
        method: GET
        user: "{{ servicenow_username }}"
        password: "{{ servicenow_password }}"
        force_basic_auth: yes
        return_content: yes
        status_code: 200
      register: table_check1
      ignore_errors: yes

    - name: Check if 'sc_item_option_mtom' table exists
      uri:
        url: "{{ servicenow_instance }}/api/now/table/sc_item_option_mtom?sysparm_limit=1"
        method: GET
        user: "{{ servicenow_username }}"
        password: "{{ servicenow_password }}"
        force_basic_auth: yes
        return_content: yes
        status_code: 200
      register: table_check2
      ignore_errors: yes

    - name: Set the variable table
      set_fact:
        variable_table: "{{ 'sc_item_option' if table_check1.status == 200 else 'sc_item_option_mtom' }}"

    - name: Debug Table Selection
      debug:
        msg: "Using table: {{ variable_table }}"

    # ✅ Step 4: Add Variables to the RITM
    - name: Add Email Variable to Request Item
      uri:
        url: "{{ servicenow_instance }}/api/now/table/{{ variable_table }}"
        method: POST
        user: "{{ servicenow_username }}"
        password: "{{ servicenow_password }}"
        force_basic_auth: yes
        headers:
          Content-Type: "application/json"
        body:
          request_item: "{{ item_sys_id }}"
          name: "user_email"
          value: "{{ user_email }}"
        body_format: json
        return_content: yes
        status_code: [200, 201]

    - name: Add Password Variable to Request Item
      uri:
        url: "{{ servicenow_instance }}/api/now/table/{{ variable_table }}"
        method: POST
        user: "{{ servicenow_username }}"
        password: "{{ servicenow_password }}"
        force_basic_auth: yes
        headers:
          Content-Type: "application/json"
        body:
          request_item: "{{ item_sys_id }}"
          name: "password"
          value: "{{ password }}"
        body_format: json
        return_content: yes
        status_code: [200, 201]

    # ✅ Step 5: Display Request Details
    - name: Display Request Details
      debug:
        msg:
          - "Catalog Request Created: {{ request_sys_id }}"
          - "Request Item ID: {{ item_sys_id }}"

    # ✅ Step 6: Retrieve and Validate RITM Variables
    - name: Retrieve RITM Variables
      uri:
        url: "{{ servicenow_instance }}/api/now/table/{{ variable_table }}?sysparm_query=request_item={{ item_sys_id }}"
        method: GET
        user: "{{ servicenow_username }}"
        password: "{{ servicenow_password }}"
        force_basic_auth: yes
        return_content: yes
        status_code: 200
      register: variables_response

    # ✅ Display Variables Response
    - name: Debug Variables Response
      debug:
        var: variables_response.json

    # ✅ Extract sys_id and values
    - name: Extract Variables
      set_fact:
        ritm_variables: >-
          {{
            variables_response.json.result | items2dict(key_name='name', value_name='value')
          }}

    # ✅ Display the Variables
    - name: Display RITM Variables
      debug:
        msg: "RITM Variables: {{ ritm_variables }}"

    # ✅ Validate the Variables
    - name: Validate Added Variables
      assert:
        that:
          - ritm_variables['user_email'] == user_email
          - ritm_variables['password'] == password
        fail_msg: "RITM variables do not match the expected values!"
        success_msg: "RITM variables are correctly added!"

