---
- name: Create ServiceNow Catalog Request for Password Reset
  hosts: localhost
  gather_facts: no

  vars:
    servicenow_instance: "https://dev247928.service-now.com"    # Replace with your instance URL
    servicenow_username: "admin"                                # ServiceNow username
    servicenow_password: "%ml4Vs9RXE/s"                         # ServiceNow password
    catalog_sys_id: "d58f4b528388e210d081f696feaad399"         # Replace with the catalog sys_id
    user_email: "Akhilakki@amitomar63gmail.onmicrosoft.com"    # User email variable
    password: "NewPassword@123"                                # Password variable

  tasks:
    # Step 1: Create Catalog Request
    - name: Create Catalog Request
      uri:
        url: "{{ servicenow_instance }}/api/now/table/sc_request"
        method: POST
        user: "{{ servicenow_username }}"
        password: "{{ servicenow_password }}"
        force_basic_auth: yes
        headers:
          Content-Type: "application/json"
        body:
          short_description: "Password reset request for {{ user_email }}"
          requested_for: "{{ servicenow_username }}"
        body_format: json
        return_content: yes
        status_code: [200, 201]
      register: request_response
      failed_when: request_response.status != 201

    - name: Extract Request ID
      set_fact:
        request_sys_id: "{{ request_response.json.result.sys_id }}"

    # Step 2: Create Request Item
    - name: Create Request Item
      uri:
        url: "{{ servicenow_instance }}/api/now/table/sc_req_item"
        method: POST
        user: "{{ servicenow_username }}"
        password: "{{ servicenow_password }}"
        force_basic_auth: yes
        headers:
          Content-Type: "application/json"
        body:
          request: "{{ request_sys_id }}"
          cat_item: "{{ catalog_sys_id }}"
          quantity: 1
        body_format: json
        return_content: yes
        status_code: [200, 201]
      register: item_response
      failed_when: item_response.status != 201

    - name: Extract Request Item ID
      set_fact:
        item_sys_id: "{{ item_response.json.result.sys_id }}"

    # Step 3: Add Variables to the Catalog Request Item
    - name: Add Email Variable to Request Item
      uri:
        url: "{{ servicenow_instance }}/api/now/table/sc_item_option_mtom"
        method: POST
        user: "{{ servicenow_username }}"
        password: "{{ servicenow_password }}"
        force_basic_auth: yes
        headers:
          Content-Type: "application/json"
        body:
          item_option.new_record: "true"
          request_item: "{{ item_sys_id }}"
          item_option.item: "user_email"
          value: "{{ user_email }}"
        body_format: json
        return_content: yes
        status_code: [200, 201]

    - name: Add Password Variable to Request Item
      uri:
        url: "{{ servicenow_instance }}/api/now/table/sc_item_option_mtom"
        method: POST
        user: "{{ servicenow_username }}"
        password: "{{ servicenow_password }}"
        force_basic_auth: yes
        headers:
          Content-Type: "application/json"
        body:
          item_option.new_record: "true"
          request_item: "{{ item_sys_id }}"
          item_option.item: "password"
          value: "{{ password }}"
        body_format: json
        return_content: yes
        status_code: [200, 201]

    # Step 4: Display Request Details
    - name: Display Request Details
      debug:
        msg:
          - "Catalog Request Created: {{ request_sys_id }}"
          - "Request Item ID: {{ item_sys_id }}"
